name: Validate WDL

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev
    workflow_dispatch:

jobs:
    validate_wdl:
      runs-on: ubuntu-latest

      steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-java@v4
            with:
                distribution: 'temurin'
                java-version: '21'

          - name: Install Dockstore CLI
            env:
              DOCKSTORE_TOKEN: ${{ secrets.DOCKSTORE_TOKEN }}
            run: |
              wget https://github.com/dockstore/dockstore-cli/releases/download/1.16.0/dockstore
              chmod +x dockstore
              mkdir -p ~/.dockstore
              printf "token: ${DOCKSTORE_TOKEN}\nserver-url: https://dockstore.org/api\n" > ~/.dockstore/config
              ./dockstore --version

          - name: Validate dockstore yaml
            run: ./dockstore yaml validate --path .

          - name: Install miniwdl and check *.wdl files
            run: |
              pipx install miniwdl
              miniwdl check --no-quant-check *.wdl
